// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DuchGorTitleFont","status":true,"description":"","parameters":{}},
{"name":"EnemyHPbar","status":true,"description":"v1.1 Pasek HP nad wrogami: kolory, płynna animacja i wartości HP.","parameters":{"BarWidth":"120","BarHeight":"10","OffsetY":"14","SmoothSpeed":"12"}}
];
